// Catastro Bogotá: sectores catastrales urbanos y mixtos. Fuente enlazada en README.
export const BARRIOS_BOGOTA = [
  "Abraham Lincoln",
  "Acacias Usaquen",
  "Acevedo Tejada",
  "Aeropuerto El Dorado",
  "Aguas Claras",
  "Aguas Claras I",
  "Alamos",
  "Alaska",
  "Alcala",
  "Alcazares",
  "Alcazares Norte",
  "Alfonso Lopez",
  "Almirante Colon",
  "Alqueria",
  "Alqueria La Fragua",
  "Alqueria La Fragua Ii",
  "Alqueria La Fragua Norte",
  "Altamira",
  "Altos De Chozica",
  "Altos De Serrezuela",
  "Altos De Suba",
  "Altos Del Poblado",
  "Altos Del Zipa",
  "Altos Del Zuque",
  "Andalucia Ii",
  "Andes Norte",
  "Antiguo Country",
  "Antonia Santos",
  "Antonio Jose De Sucre",
  "Arabia",
  "Arabia I",
  "Arabia Ii",
  "Arboleda Santa Teresita",
  "Arboleda Sur",
  "Arborizadora Alta",
  "Arborizadora Alta Ii",
  "Arborizadora Alta I",
  "Arborizadora Baja",
  "Area Artilleria",
  "Argelia Ii",
  "Armenia",
  "Arrayanes I",
  "Arrayanes V",
  "Arrayanes Vi",
  "Atahualpa",
  "Atenas",
  "Atlanta",
  "Aures",
  "Aures Ii",
  "Autopista Medellin",
  "Autopista Muzu",
  "Autopista Muzu Oriental",
  "Autopista Sur",
  "Banco Central",
  "Baquero",
  "Barcelona",
  "Barcelona Sur",
  "Barlovento",
  "Barrancas",
  "Barrancas Norte",
  "Barrancas Oriental I",
  "Barranquillita",
  "Batallon Caldas",
  "Batan",
  "Bavaria",
  "Belalcazar",
  "Belen",
  "Belen Fontibon",
  "Bella Flor",
  "Bella Flor Sur",
  "Bella Suiza",
  "Bellavista",
  "Bellavista Lucero Alto",
  "Bellavista Occidental",
  "Bellavista Sur",
  "Bello Horizonte",
  "Benjamin Herrera",
  "Berlin",
  "Betania",
  "Bilbao",
  "Bochica",
  "Bochica Ii",
  "Boita",
  "Bolivia",
  "Bolivia Oriental",
  "Bolonia",
  "Bolonia I",
  "Bonanza",
  "Bosa",
  "Bosa 37",
  "Bosa Nova",
  "Bosa Nova El Porvenir",
  "Bosque Calderon",
  "Bosque De Los Alpes",
  "Bosque De Modelia",
  "Bosque De Pinos",
  "Bosque De Pinos I",
  "Bosque De Pinos Iii",
  "Bosque Izquierdo",
  "Bosque Popular",
  "Bosques De San Jorge",
  "Boyaca",
  "Brasil",
  "Brasilia",
  "Bravo Paez",
  "Brazuelos Occidental",
  "Brisas Aldea Fontibon",
  "Brisas Del Llano",
  "Brisas Del Volador",
  "Britalia",
  "Buenavista",
  "Buenos Aires",
  "Calandaima",
  "Callejon Santa Barbara",
  "Calvo Sur",
  "Campanella",
  "Campin",
  "Campin Occidental",
  "Campo Eucaristico",
  "Campo Hermoso",
  "Campo Verde",
  "Canada O Guira",
  "Canaima",
  "Canaveralejo",
  "Canaveralejo Rural",
  "Candelaria La Nueva",
  "Canodromo",
  "Cantagallo",
  "Caobos Salazar",
  "Capellania",
  "Caracas",
  "Caracoli",
  "Carmen Del Sol",
  "Casa Blanca Suba I",
  "Casa Blanca Suba Iii",
  "Casa Blanca Sur",
  "Casa De Teja",
  "Casablanca",
  "Casablanca Suba",
  "Casablanca Suba Otoño",
  "Casablanca Suba Urbano",
  "Casablanca Suba Urbano I",
  "Casablanca Suba Urbano Ii",
  "Castilla",
  "Catalina",
  "Catalina Ii",
  "Cataluna",
  "Cañaveralejo I",
  "Cedritos",
  "Cedritos Del Sur",
  "Cedro Narvaez",
  "Cedro Salazar",
  "Cementerio Jardines Apogeo",
  "Centenario",
  "Central De Mezclas",
  "Centro Administrativo",
  "Centro Administrativo Occ.",
  "Centro Engativa Ii",
  "Centro Fontibon",
  "Centro Industrial",
  "Centro Narino",
  "Centro Usme",
  "Centro Usme Urbano",
  "Centro Usme Urbano I",
  "Cerro Colorado",
  "Cerros De Oriente",
  "Chapinerito",
  "Chapinero Central",
  "Chapinero Norte",
  "Chapinero Occidental",
  "Charala",
  "Charco Urbano",
  "Charles De Gaulle",
  "Chicala",
  "Chico Norte",
  "Chico Norte Ii Sector",
  "Chico Norte Iii Sector",
  "Chico Sur",
  "Chiguaza Urbano",
  "Chorillos",
  "Chucua De La Vaca I",
  "Chucua De La Vaca Ii",
  "Chucua De La Vaca Iii",
  "Chuniza",
  "Ciudad Bachue",
  "Ciudad Bachue I Etapa",
  "Ciudad Bachue Ii",
  "Ciudad Berna",
  "Ciudad Bolivar",
  "Ciudad De Cali",
  "Ciudad Hayuelos",
  "Ciudad Hunza",
  "Ciudad Jardin Norte",
  "Ciudad Jardin Sur",
  "Ciudad Kennedy",
  "Ciudad Kennedy Central",
  "Ciudad Kennedy Norte",
  "Ciudad Kennedy Occidental",
  "Ciudad Kennedy Oriental",
  "Ciudad Kennedy Sur",
  "Ciudad Londres I",
  "Ciudad Salitre Nor-oriental",
  "Ciudad Salitre Sur-oriental",
  "Ciudad Techo Ii",
  "Ciudad Universitaria",
  "Ciudadela Colsubsidio",
  "Ciudadela El Recreo",
  "Ciudadela El Recreo Ii",
  "Claret",
  "Class",
  "Club De Los Lagartos",
  "Colmena I Los Pinares",
  "Colombia",
  "Colon",
  "Colseguros",
  "Compartir",
  "Comuneros",
  "Concepcion Norte",
  "Conejera",
  "Cooperativa De Sub-oficiales",
  "Corabastos",
  "Cordillera Del Sur",
  "Cordoba",
  "Corredor Ferreo Del Sur",
  "Costa Azul",
  "Country Club",
  "Cundinamarca",
  "Danubio",
  "Danubio Ii",
  "Delmonte",
  "Desarrollo Brazuelos",
  "Desarrollo Brazuelos I",
  "Diana Turbay",
  "Diana Turbay Arrayanes",
  "Diana Turbay Cultivos",
  "Dindalito",
  "Dintalito",
  "Doce De Octubre",
  "Dona Liliana",
  "Dorado Industrial I",
  "Duitama",
  "Eduardo Frey",
  "Eduardo Santos",
  "Egipto",
  "El Bagazal",
  "El Bosque",
  "El Bosque Central I",
  "El Bosque Sur Oriental Rural Iii",
  "El Carmelo",
  "El Carmen",
  "El Carmen Fontibon",
  "El Cedro",
  "El Cedro I",
  "El Cerezo",
  "El Chanco I",
  "El Chanco Ii",
  "El Chanco Iii",
  "El Charco",
  "El Chico",
  "El Chircal Sur",
  "El Contador",
  "El Cortijo",
  "El Corzo",
  "El Corzo I",
  "El Corzo Ii",
  "El Curubo",
  "El Danubio Azul",
  "El Destino",
  "El Dorado",
  "El Dorado Industrial",
  "El Ejido",
  "El Encanto",
  "El Ensueno",
  "El Gaco",
  "El Guavio",
  "El Jardin",
  "El Jazmin",
  "El Laurel",
  "El Liston",
  "El Madrigal",
  "El Minuto De Dios",
  "El Minuto De Maria",
  "El Mirador",
  "El Mirador De La Estancia",
  "El Mirador Ii",
  "El Mochuelo",
  "El Mochuelo Ii Norte",
  "El Mochuelo Ii Urbano",
  "El Mochuelo Oriental",
  "El Mochuelo Urbano",
  "El Muelle",
  "El Nevado",
  "El Nevado Ii",
  "El Nogal",
  "El Nuevo Portal",
  "El Nuevo Portal Ii",
  "El Nuevo Portal Ii Rural",
  "El Otoño",
  "El Otoño I",
  "El Paraiso",
  "El Paraiso Bosa",
  "El Pedregal",
  "El Pedregal Ii",
  "El Penon Del Cortijo",
  "El Pinar",
  "El Pino",
  "El Plan",
  "El Playon",
  "El Poa",
  "El Portal Del Brasil",
  "El Portal Del Divino",
  "El Portal Urbano",
  "El Progreso",
  "El Progreso Usme",
  "El Real",
  "El Recuerdo",
  "El Redil",
  "El Refugio",
  "El Refugio I",
  "El Refugio Ii",
  "El Refugio Zona Ii",
  "El Remanso",
  "El Remanso I",
  "El Retazo",
  "El Retiro",
  "El Rincon",
  "El Rincon Norte",
  "El Rocio",
  "El Rocio Norte",
  "El Rosario",
  "El Rubi",
  "El Salitre",
  "El Salteador",
  "El Satelite",
  "El Tesoro",
  "El Tintal Central",
  "El Tintal Ii",
  "El Tintal Iii",
  "El Tintal Iv",
  "El Toberin",
  "El Triangulo",
  "El Triangulo I",
  "El Triangulo Ii",
  "El Tuno",
  "El Uval",
  "El Uval I",
  "El Uval Ii",
  "El Uval Iii",
  "El Vergel",
  "El Vergel Oriental",
  "El Vervenal",
  "El Virrey",
  "Emaus",
  "Engativa Zona Urbana",
  "Entrerios",
  "Escocia",
  "Escuela De Caballeria I",
  "Escuela De Caballeria Ii",
  "Escuela De Carabineros",
  "Escuela De Infanteria",
  "Escuela General Santander",
  "Escuela Militar",
  "Espartillal",
  "Espino",
  "Espino I",
  "Estacion Central",
  "Estoril",
  "Estrella",
  "Estrella Del Norte",
  "Estrella Del Sur",
  "Fatima",
  "Ferrocaja Fontibon",
  "Fiscala Alta",
  "Florencia",
  "Florida",
  "Florida Blanca",
  "Franco",
  "Galan",
  "Galan Rural",
  "Galerias",
  "Galicia",
  "Garces Navas",
  "Garces Navas Oriental",
  "Garces Navas Sur",
  "Gibraltar Sur",
  "Gilmar",
  "Ginebra",
  "Ginebra Ii",
  "Girardot",
  "Gorgonzola",
  "Gran America",
  "Gran Britalia",
  "Gran Britalia I",
  "Gran Colombiano",
  "Gran Granada",
  "Gran Yomasa",
  "Granada",
  "Granada Norte",
  "Granada Sur",
  "Granjas De Santa Sofia",
  "Granjas De Techo",
  "Granjas San Pablo",
  "Guadalupe",
  "Guadual Fontibon",
  "Gualoche",
  "Guiparma",
  "Gustavo Restrepo",
  "Hipotecho",
  "Hipotecho Occidental",
  "Hipotecho Sur",
  "Horizontes Norte",
  "Hospital San Carlos",
  "Iberia",
  "Industrial Centenario",
  "Ingemar",
  "Ingemar I",
  "Ingemar Oriental I",
  "Ingemar Oriental Ii",
  "Ingles",
  "Interindustrial",
  "Iragua",
  "Isla Del Sol",
  "Islandia",
  "Ismael Perdomo",
  "Jacqueline",
  "Jardin Botanico",
  "Jerusalen",
  "Jimenez De Quesada",
  "Jimenez De Quesada Ii Sector",
  "Jorge Eliecer Gaitan",
  "Jorge Gaitan Cortes",
  "Jorge Uribe Botero",
  "Jose Antonio Galan",
  "Jose Joaquin Vargas",
  "Jose Maria Carbonel",
  "Juan Jose Rondon",
  "Juan Jose Rondon I",
  "Juan Pablo Ii",
  "Juan Rey (la Paz)",
  "Juan Rey Sur",
  "Juan Xxiii",
  "Julio Florez",
  "Kasandra",
  "La Alameda",
  "La Andrea",
  "La Asuncion",
  "La Aurora",
  "La Belleza",
  "La Cabana",
  "La Cabana Fontibon",
  "La Cabrera",
  "La Calleja",
  "La Camelia",
  "La Camelia Ii",
  "La Campina",
  "La Candelaria",
  "La Capuchina",
  "La Carolina",
  "La Carolina De Suba",
  "La Castellana",
  "La Catedral",
  "La Cecilia",
  "La Chucua",
  "La Cita",
  "La Comuna",
  "La Concordia",
  "La Coruna",
  "La Esmeralda",
  "La Esperanza",
  "La Esperanza De Usme",
  "La Esperanza Norte",
  "La Esperanza Sur",
  "La Esperanza Sur I",
  "La Estacion Bosa",
  "La Estancia",
  "La Estanzuela",
  "La Estrada",
  "La Estradita",
  "La Estrellita",
  "La Estrellita I",
  "La Estrellita Iii",
  "La Faena",
  "La Favorita",
  "La Fiscala",
  "La Fiscala Norte",
  "La Florida Occidental",
  "La Fragua",
  "La Fraguita",
  "La Gaitana",
  "La Gaitana Oriental",
  "La Giralda",
  "La Gloria Occidental",
  "La Gloria Oriental",
  "La Granja",
  "La Granja Norte",
  "La Hortua",
  "La Huerta",
  "La Independencia",
  "La Laguna Fontibon",
  "La Liberia",
  "La Libertad",
  "La Macarena",
  "La Magdalena",
  "La Magdalena I",
  "La Maria",
  "La Marichuela",
  "La Merced",
  "La Merced Norte",
  "La Orquidea De Usme",
  "La Pampa",
  "La Patria",
  "La Paz",
  "La Paz Bosa",
  "La Pena",
  "La Pepita",
  "La Perseverancia",
  "La Perseverancia I",
  "La Peña I",
  "La Peña Rural",
  "La Picota",
  "La Picota Oriental",
  "La Pradera",
  "La Pradera Norte",
  "La Primavera I",
  "La Reforma",
  "La Requilina",
  "La Resurreccion",
  "La Resurreccion I",
  "La Riviera",
  "La Sabana",
  "La Salle",
  "La Serena",
  "La Soledad",
  "La Soledad Norte",
  "La Torre",
  "La Trinidad",
  "La Union Urbano",
  "La Uribe",
  "La Valvanera",
  "La Vega San Bernardino",
  "La Victoria",
  "Lago De Suba",
  "Lago Gaitan",
  "Lagunitas",
  "Lagunitas Urbano",
  "Las Acacias",
  "Las Acacias Rural",
  "Las Aguas",
  "Las Americas",
  "Las Brisas",
  "Las Cruces",
  "Las Delicias",
  "Las Delicias Del Carmen Ii Sector",
  "Las Dos Avenidas",
  "Las Ferias",
  "Las Ferias Occidental",
  "Las Flores",
  "Las Gaviotas",
  "Las Guacamayas I",
  "Las Guacamayas Ii",
  "Las Guacamayas Iii",
  "Las Guacamayas Iv",
  "Las Lomas",
  "Las Manas",
  "Las Margaritas",
  "Las Mercedes",
  "Las Mercedes I",
  "Las Mercedes Suba",
  "Las Navetas",
  "Las Nieves",
  "Las Orquideas",
  "Las Villas",
  "Las Violetas",
  "Lech Walesa",
  "Libertador",
  "Lisboa",
  "Llano Grande",
  "Lombardia",
  "Los Alamos",
  "Los Almendros",
  "Los Alpes",
  "Los Alpes Sur",
  "Los Andes",
  "Los Angeles",
  "Los Arrayanes Ii",
  "Los Cedros",
  "Los Cedros Oriental",
  "Los Cerezos",
  "Los Ejidos",
  "Los Laches",
  "Los Laureles",
  "Los Laureles Ii",
  "Los Laureles Sur Oriental I",
  "Los Libertadores",
  "Los Molinos",
  "Los Naranjos",
  "Los Olivares",
  "Los Rosales",
  "Los Sauces",
  "Los Soches",
  "Los Tres Reyes",
  "Los Tres Reyes I",
  "Lourdes",
  "Lucero Alto",
  "Lucero Del Sur",
  "Luis Carlos Galan",
  "Lusitania",
  "Madelena",
  "Mandalay",
  "Marandu",
  "Marco Fidel Suarez",
  "Marco Fidel Suarez I",
  "Maria Cano",
  "Maria Cristina",
  "Maria Paz",
  "Marly",
  "Marruecos",
  "Marsella",
  "Mazuren",
  "Meissen",
  "Metropolis",
  "Mexico",
  "Millan",
  "Mirador Del Norte",
  "Mirandela",
  "Mochuelo Alto Urbano",
  "Mochuelo V",
  "Modelia",
  "Modelia Occidental",
  "Modelo Sur",
  "Molinos De Oriente",
  "Molinos Del Sur",
  "Molinos Norte",
  "Monaco",
  "Monte Carlo",
  "Montebello",
  "Monteblanco",
  "Montes",
  "Montevideo",
  "Moralba",
  "Moravia",
  "Muequeta",
  "Murillo Toro",
  "Muzu",
  "Naciones Unidas",
  "Narino Sur",
  "Nazareth Urbano",
  "Nicolas De Federman",
  "Niza Norte",
  "Niza Suba",
  "Niza Sur",
  "Normandia",
  "Normandia Occidental",
  "Nuestra Senora Del Rosario",
  "Nueva Delhi",
  "Nueva Esperanza",
  "Nueva Gloria",
  "Nueva Granada",
  "Nueva Granada Bosa",
  "Nueva Tibabuyes",
  "Nueva York",
  "Nueva Zelandia",
  "Nuevo Muzu",
  "Nuevo San Andres",
  "Nuevo Techo",
  "Olarte",
  "Olaya",
  "Once De Noviembre",
  "Ortezal",
  "Osorio",
  "Osorio Iii",
  "Osorio Iv",
  "Osorio X Urbano",
  "Osorio Xii",
  "Ospina Perez",
  "Ospina Perez Sur",
  "Pablo Vi Norte",
  "Palermo",
  "Palermo Sur",
  "Palo Blanco",
  "Paloquemao",
  "Paraiso Quiba",
  "Paramo Iv",
  "Paramo Rural V",
  "Paramo Urbano",
  "Paramo Urbano I",
  "Parcela El Porvenir",
  "Pardo Rubio",
  "Pardo Rubio I",
  "Paris",
  "Paris Gaitan",
  "Parque Distrital Salitre",
  "Parque El Tunal",
  "Parque Nacional",
  "Parque Nacional Urbano",
  "Parque Popular Salitre",
  "Pasadena",
  "Paso Ancho",
  "Pasquilla Urbana",
  "Pastrana",
  "Patio Bonito",
  "Patio Bonito Ii",
  "Patio Bonito Iii",
  "Paulo Vi",
  "Pensilvania",
  "Perdomo Alto",
  "Pinos De Lombardia",
  "Pio Xii",
  "Policarpa",
  "Polo Club",
  "Popular Modelo",
  "Porciuncula",
  "Portal",
  "Portales Del Norte",
  "Porvenir",
  "Potosi",
  "Potrerillo",
  "Prado Pinzon",
  "Prado Veraniego",
  "Prado Veraniego Norte",
  "Prado Veraniego Sur",
  "Primavera",
  "Primavera Ii",
  "Primavera Occidental",
  "Primero De Mayo",
  "Provivienda",
  "Provivienda Norte",
  "Provivienda Occidental",
  "Provivienda Oriental",
  "Pueblo Viejo",
  "Puente Aranda",
  "Puente Colorado",
  "Puente Grande",
  "Puente Largo",
  "Puerta Al Llano De Usme",
  "Puerta Al Llano I",
  "Puerta Al Llano Rural",
  "Puerta De Teja",
  "Puerta Del Sol",
  "Puerto Rico",
  "Quesada",
  "Quiba",
  "Quiba Bajo I",
  "Quiba Bajo Ii",
  "Quiba Bajo Iii",
  "Quiba Bajo Iv",
  "Quiba Bajo Urbano",
  "Quiba Bajo V",
  "Quiba I",
  "Quiba Rural",
  "Quiba Urbano",
  "Quindio",
  "Quinta Camacho",
  "Quinta Mutis",
  "Quinta Paredes",
  "Quinta Ramos",
  "Quintas Del Sur",
  "Quirigua I",
  "Quirigua Ii",
  "Quirigua Oriental",
  "Quiroga",
  "Quiroga Central",
  "Quiroga I",
  "Quiroga Sur",
  "Rafael Escamilla",
  "Rafael Nunez",
  "Rafael Uribe",
  "Ramajal",
  "Ramirez",
  "Remanso",
  "Remanso Sur",
  "Remanso Urbano",
  "Renania Urapanes",
  "Restrepo",
  "Restrepo Occidental",
  "Ricaurte",
  "Rincon Altamar",
  "Rincon De Galicia",
  "Rincon De La Valvanera",
  "Rincon De Santa Ines",
  "Rincon De Suba",
  "Rincon Del Chico",
  "Rionegro",
  "Roma",
  "Ronda",
  "Sabana De Tibabuyes",
  "Sabana De Tibabuyes Norte",
  "Sabana Del Dorado",
  "Sabana Grande",
  "Sagrado Corazon",
  "Salazar Gomez",
  "Salazar Usme",
  "Salitre Occidental",
  "Salitre Suba",
  "Samore",
  "Samper",
  "Samper Mendoza",
  "San Agustin",
  "San Antonio",
  "San Antonio Del Mirador",
  "San Antonio Engativa",
  "San Antonio Noroccidental",
  "San Antonio Norte",
  "San Antonio Urbano",
  "San Benito",
  "San Bernardino I",
  "San Bernardino Ii",
  "San Bernardino Potreritos",
  "San Bernardino Xix",
  "San Bernardino Xviii",
  "San Bernardino Xxii Urbano",
  "San Bernardino Xxv Urbano",
  "San Bernardo",
  "San Blas",
  "San Blas Ii",
  "San Carlos",
  "San Carlos De Suba",
  "San Cayetano",
  "San Cristobal Norte",
  "San Cristobal Sur",
  "San Diego",
  "San Diego-bosa",
  "San Eusebio",
  "San Felipe",
  "San Felipe De Usme",
  "San Felipe De Usme Rural",
  "San Fernando",
  "San Fernando Occidental",
  "San Francisco",
  "San Francisco Rural",
  "San Gabriel",
  "San Gabriel Norte",
  "San Gabriel Norte Ii",
  "San Ignacio",
  "San Isidro",
  "San Isidro Rural",
  "San Isidro Rural Ii",
  "San Javier",
  "San Joaquin",
  "San Jorge Sur",
  "San Jose De Bavaria",
  "San Jose De Fontibon",
  "San Jose De Usaquen",
  "San Jose Del Prado",
  "San Jose Sur",
  "San Jose Sur Oriental",
  "San Jose V Sector",
  "San Juan Bautista",
  "San Juan Urbano",
  "San Luis",
  "San Luis Altos Del Cabo Rural",
  "San Luis Altos Del Cabo Rural Ii",
  "San Martin",
  "San Martin Sur",
  "San Miguel",
  "San Pablo Bosa",
  "San Pablo Jerico",
  "San Patricio",
  "San Pedro",
  "San Pedro De Los Robles",
  "San Pedro Sur",
  "San Rafael",
  "San Rafael Industrial",
  "San Rafael Usme",
  "San Vicente",
  "San Vicente Ferrer",
  "San Victorino",
  "Santa Ana",
  "Santa Ana Occidental",
  "Santa Ana Sur",
  "Santa Barbara",
  "Santa Barbara Central",
  "Santa Barbara Occidental",
  "Santa Barbara Oriental",
  "Santa Bibiana",
  "Santa Catalina",
  "Santa Cecilia",
  "Santa Cecilia De Suba I",
  "Santa Cecilia De Suba Ii",
  "Santa Cecilia Puente Norte",
  "Santa Fe",
  "Santa Fe Bosa",
  "Santa Helena",
  "Santa Helenita",
  "Santa Ines",
  "Santa Ines Sur",
  "Santa Ines Sur Ii",
  "Santa Isabel",
  "Santa Isabel Sur",
  "Santa Librada",
  "Santa Librada Norte",
  "Santa Lucia",
  "Santa Maria",
  "Santa Matilde",
  "Santa Monica",
  "Santa Rita De Suba",
  "Santa Rita Sur Oriental",
  "Santa Rosa",
  "Santa Sofia",
  "Santa Teresa",
  "Santa Teresa De Suba",
  "Santa Teresita",
  "Santa Viviana",
  "Santander",
  "Santander Sur",
  "Santiago Perez",
  "Santo Domingo",
  "Saucedal",
  "Segundo Contador",
  "Seminario",
  "Sena",
  "Serranias",
  "Serranias I",
  "Sevilla",
  "Siberia Central",
  "Siberia Ii",
  "Siberia Urbano",
  "Sierra Morena",
  "Sierra Morena Ii",
  "Siete De Agosto",
  "Simon Bolivar",
  "Sociego",
  "Sosiego Sur",
  "Sotavento",
  "Suba Cerros",
  "Suba Urbano",
  "Sucre",
  "Sumapaz",
  "Suramerica",
  "Tabora",
  "Tairona",
  "Techo",
  "Tejar",
  "Terminal De Transportes",
  "Teusaquillo",
  "Tibabita",
  "Tibabita El Rosario",
  "Tibabita I",
  "Tibabuyes",
  "Tibabuyes Ii",
  "Tibabuyes Occidental",
  "Tibabuyes Universal",
  "Tibana",
  "Tibaque I",
  "Tibaque Ii",
  "Tibaque Iii",
  "Tibaque Urbano",
  "Tihuaque",
  "Timiza",
  "Timiza A",
  "Timiza B",
  "Timiza C",
  "Tintala",
  "Tintalito",
  "Tocaimita Oriental",
  "Tocaimita Oriental I",
  "Tocarema",
  "Torca",
  "Torca I",
  "Torca Ii",
  "Torca Iii",
  "Toscana",
  "Ttes De Colombia",
  "Tuna",
  "Tuna Alta",
  "Tuna Baja",
  "Tunal Oriental",
  "Tundama",
  "Tunjuelito",
  "Usaquen",
  "Usatama",
  "Usminia",
  "Valladolid",
  "Veinte De Julio",
  "Velodromo",
  "Venecia",
  "Venecia Occidental",
  "Veracruz",
  "Veraguas",
  "Verbenal San Antonio",
  "Vereda El Tintal",
  "Vereda El Tintal Urbano",
  "Vereda Suba Cerros Ii",
  "Vereda Suba Naranjos",
  "Vergel Occidental",
  "Verona",
  "Versalles Fontibon",
  "Victoria Norte",
  "Villa Alcazar",
  "Villa Alsacia",
  "Villa Alsacia Ii",
  "Villa Amalia",
  "Villa Anita",
  "Villa Anny I",
  "Villa Anny Ii",
  "Villa Candelaria",
  "Villa Carmenza",
  "Villa De Los Alpes",
  "Villa De Los Alpes I",
  "Villa Del Cerro",
  "Villa Del Mar",
  "Villa Del Prado",
  "Villa Del Rio",
  "Villa Diana",
  "Villa Elisa",
  "Villa Emma",
  "Villa Gladys",
  "Villa Gloria",
  "Villa Hermosa",
  "Villa Israel",
  "Villa Luz",
  "Villa Maria",
  "Villa Maria I",
  "Villa Mayor",
  "Villa Mayor Oriental",
  "Villa Nelly Iii Sector",
  "Villa Sagrario",
  "Villabel",
  "Villas De Alcala",
  "Villas De Granada",
  "Villas De Granada I",
  "Villas Del Progreso",
  "Villas El Diamante",
  "Villemar",
  "Vision De Oriente",
  "Vitelma",
  "Voto Nacional",
  "Yomasa",
  "Yomasa Norte",
  "Zona Franca",
] as const
